# Generated by Django 2.2.2 on 2019-06-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100, verbose_name='问题')),
                ('reason', models.CharField(max_length=100, verbose_name='原因')),
                ('solution', models.TextField(verbose_name='解决方案')),
            ],
        ),
    ]
